services:
  pricewatch:
    image: ghcr.io/litmanennn/pricewatch:latest

    container_name: pricewatch

    environment:
      TZ: Europe/Helsinki
      DB_FILE_NAME: /app/data/pricewatch.db
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      PRICE_CHECK_INTERVAL_HOURS: ${PRICE_CHECK_INTERVAL_HOURS:-6}

    volumes:
      - /DATA/AppData/pricewatch:/app/data

    ports:
      - "3000:3000"

    restart: unless-stopped

    networks:
      - media_net


networks:
  media_net:
    external: true